### ISSUE TITLE
Lab Report Instructions missing

### ISSUE THREAD

**Issue by RamtinTJB** [ucsd-cse15l-f23/ucsd-cse15l-f23.github.io#2]
https://github.com/ucsd-cse15l-f23/ucsd-cse15l-f23.github.io/blob/35462423372a99bfc56040abf050cf816c873b94/_posts/weeks/2023-11-27-week9.md?plain=1#L21C1-L21C26

This line should contain the link to the instructions for the last lab report :)

**Comment by orielsanchez** [comment]
FAX

**Comment by pandrew99** [comment]
@orielsanchez @RamtinTJB The instructions for lab report 5 is now posted! Thanks for your patience :)
